### ISSUE TITLE
Only output whitelist= lines when feature is being used

### ISSUE THREAD

**Issue by radix42** [MyHush/config-generator#2]
A line in the config that is just:
```
whitelist=
````
with no hosts specified is an invalid config, and returns the error:
```
 Error: Invalid netmask specified in -whitelist: ''
```
when a line like that is in the generated conf file.  So we shouldn't include that in the generated config unless the whitelist feature is being used.

**Comment by matthewjamesr** [comment]
Closed by 4c8470452cf927056d6edcd5bfdae7561caa557a
