### ISSUE TITLE
Update for v3 mainnet

### ISSUE THREAD

**Issue by leto** [MyHush/config-generator#9]
location is now ~/.komodo/HUSH3

txindex=1 is now  required

Currently SilentDragon also enables these indexes by default:
```
addressindex=1
spentindex=1
timestampindex=1
```

so it would be cool to have those enabled by default but able to be turned off.

@matthewjamesr here you go!

**Comment by matthewjamesr** [comment]
@leto What is the location for conf on Mac OS?

**Comment by leto** [comment]
this is done, thanks!
